@url= http://localhost:5000

### Home
GET {{url}}

### Users
GET {{url}}/users

### Books
GET {{url}}/books

### create user / signup
POST {{url}}/users
Content-Type: application/json

{
    "name": "Luis",
    "email": "luis@gmail.com",
    "password": "luis"
}

### login user
POST {{url}}/users/login
Content-Type: application/json

{
    "email": "luis@gmail.com",
    "password": "luis"
}
