@url= http://localhost:5000

### Home
GET {{url}}

### Uers
GET {{url}}/users

### Books
GET {{url}}/books

### User Create
POST {{url}}/users
Content-Type: application/json

{
    "name": "Luis",
    "email": "luis@gmail.com",
    "password": "luis"
}