@url= http://localhost:5000

### Home
GET {{url}}

### Uers
GET {{url}}/users

### Books
GET {{url}}/books

### User Create
POST {{url}}/users
Content-Type: application/json

{
    "name": "niko",
    "email": "niko@gmail.com",
    "password": "niko"
}

### User LOGIN
POST {{url}}/users/login
Content-Type: application/json

{
"email": "niko@gmail.com",
"password": "niko"
}

### User LOGOUT
GET {{url}}/users/logout