@url= http://localhost:5000

### Home
GET {{url}}

### Books
GET {{url}}/books

### Uers
GET {{url}}/users

### Me / Chek if I am still logged in and give me my user info
GET {{url}}/users/me

### User Create
POST {{url}}/users
Content-Type: application/json

{
    "name": "lisa",
    "email": "lisa@gmail.com",
    "password": "lisa"
}

### User LOGIN
POST {{url}}/users/login
Content-Type: application/json

{
"email": "lisa@gmail.com",
"password": "lisa"
}

### User LOGOUT
GET {{url}}/users/logout